- name: Download Linux Perl Installer
  ansible.builtin.get_url:
    url: "{{ perl_url_glpi_agent }}"
    dest: ~/
    mode: '0774'
  register: glpi_agent_download
  
- debug: 
    msg: "{{ glpi_agent_download.dest }}"

- name: Garante agente instalado e server configurado
  ansible.builtin.shell: 
    chdir: ~/
    cmd: 'perl glpi-agent-{{ glpi_agent_version }}-linux-installer.pl --server={{ server }}'
  register: glpi_agent_install

- debug: 
    msg: "{{ glpi_agent_install}}"
